// <auto-generated />
namespace food_express.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dishname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dishname));
        
        string IMigrationMetadata.Id
        {
            get { return "202103030425416_dish-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
