// <auto-generated />
namespace food_express.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderdishcount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderdishcount));
        
        string IMigrationMetadata.Id
        {
            get { return "202103110646187_order-dish-count"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
